### ISSUE TITLE
ACCEPTANCE TESTING: Undo updates filtered list to show entire list

### ISSUE THREAD

**Issue by itsdickson** [CS2103AUG2017-T16-B1/main#159]
I'm assuming the predicate used for UNDO is SHOW_ALL_PERSONS instead of the list that the user is currently in?

Example:
after `find bernice` and `delete 2` commands
![image](https://user-images.githubusercontent.com/30717938/32363949-ed093410-c0ac-11e7-82d2-3103b2001c93.png)

after undo:
![image](https://user-images.githubusercontent.com/30717938/32363986-204d1dbe-c0ad-11e7-88ca-00552bbc0e68.png)

**Comment by Kennard123661** [comment]
Hi @itsdickson , thanks for pointing this issue out. I went to try breaking that feature as well. And yes, the issue you pointed out is a valid issue because it might seem less intuitive for the user. 

However, if I were to do the reverse and `delete 2` then `find bernice`, and let the listing remain as a `find bernice` Predicate, it would mean that the user has no way to see that his command has been undone, since Joh not  would be listed if I had used the `find bernice` predicate. 

I feel that the intention of listing all is to allow verification that the command has been undone. If I change the listing to remain the same at `find bernice`, it becomes more difficult for the user to verify that `John` is added back into Ark.

I feel that it is more important for the user to verify that his previous command has been undone. Hence, we would allow this feature to remain as it is. Thank you for raising this issue with us once again. it took us awhile to discuss this issue and come to a consensus on how we should deal with it. Many thanks.
